question_index:
    path:     /
    defaults: { _controller: "XTeamPlatformBundle:Question:index" }
    methods:  GET

question_search:
    path:     /search
    defaults: { _controller: "XTeamPlatformBundle:Question:search" }
    methods:  GET

question_show:
    path:     /{id}/show/
    defaults:
        _controller: "XTeamPlatformBundle:Question:show"
    methods:  [GET, POST]

question_new:
    path:     /new
    defaults: { _controller: "XTeamPlatformBundle:Question:new" }
    methods:  [GET, POST]

question_edit:
    path:     /{id}/edit
    defaults: { _controller: "XTeamPlatformBundle:Question:edit" }
    methods:  [GET, POST]

question_delete:
    path:     /{id}/delete
    defaults: { _controller: "XTeamPlatformBundle:Question:delete" }
    methods:  DELETE

